#005 Mooshak
a.out: 005.o Cuac.o Fecha.o Interprete.o Lista.o
	g++ 005.o Cuac.o Fecha.o Interprete.o Lista.o

005.o: 005.cpp
	g++ -c 005.cpp
Cuac.o: Cuac.cpp Cuac.h
	g++ -c Cuac.cpp 
Fecha.o: Fecha.cpp Fecha.h
	g++ -c Fecha.cpp
Interprete.o: Interprete.cpp Interprete.h
	g++ -c Interprete.cpp 
Lista.o: Lista.cpp Lista.h
	g++ -c Lista.cpp
